### ISSUE TITLE
Dealing with Time Zones

### ISSUE THREAD

**Issue by dylanglockler** [sugi/jquery-gcal-flow#14]
I have an event in my calendar occurring from 7-9PM in the central time zone. I want the time to display as 7-9PM for everyone, no matter where they are browsing from, but it's displaying as 8-10PM where I am on the East Coast. Is there some way to control this so that it displays the time the event will occur in the time zone it will occur in? 

The website is www.jasonkfriedman.com.

**Comment by Dhirajpatel** [comment]
Hello,
Can we set pacific time zone?
