### ISSUE TITLE
Enable link on item location with GoogleMap

### ISSUE THREAD

**Issue by ubaid89** [sugi/jquery-gcal-flow#33]
Enable link on item location with GoogleMap '' link_item_location: true ", some google calender events have google map link but some events have not google map link, in this case plugin give error, so i added this condition.... plugin working perfect

if (this.opts.link_item_location) {
     /*  this condition */
      if (ent.location != undefined) {
       }
   /*   */
} else {
   /*  this condition */
      if (ent.location != undefined) {
       }
   /*   */
} 

please added this condition in your plugin......thank you

**Comment by sugi** [comment]
Thank you reporting.
I fixed with 649b4047ef6205abad075064c92127a2a91ffcda and release v3.0.2.
