### ISSUE TITLE
Is there a way to include onClick event on a tag?

### ISSUE THREAD

**Issue by avoxxSolutions** [sugi/jquery-gcal-flow#38]
Hi,

I would like to include an onClick facility on the a tags instead of having the href.. Is there a way to do this?

I want to do this as I am using this plugin on a mobile app and when I click it, instead of opening the calendar app, it is currently opening a web page.

Regards,
Keith Spiteri

**Comment by sugi** [comment]
I think you can use "callback" option to set event handler on dom built by the plugin.
However, here're no way to access original json data, currently.
